### get employees
GET http://localhost:3000/api/employees

###
POST http://localhost:3000/api/employees
Content-Type: application/json

{
  "name": "Albert Einstein",
  "salary": 17000
}

### Get employee by id
GET http://localhost:3000/api/employees/1

### Update an employee
PATCH http://localhost:3000/api/employees/1
Content-Type: application/json

{
  "name": "John Doe",
  "salary": 700
}